# Generated by Django 5.2 on 2025-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "-created_at")},
        ),
    ]
